name: Build Firmware

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Cache PlatformIO core, packages, and pip cache for faster builds
      # Key includes hash of platformio.ini to invalidate cache when dependencies change
      - name: Cache PlatformIO and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            ~/.cache/pip
            .pio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build firmware
        run: platformio run -e default

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ github.ref_name }} # e.g., firmware-v1.0.0 or firmware-main
          path: |
            .pio/build/default/firmware.bin
          if-no-files-found: error
