name: PlatformIO CI

on: [push]

jobs:
  common:
    runs-on: ubuntu-latest
    outputs:
      platformio_installed: ${{ steps.install_platformio.outcome }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache PlatformIO and pip
        uses: actions/cache@v4
        with:
          path: |-
            ~/.platformio
            ~/.cache/pip
          key: ${{ runner.os }}-platformio-pip-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-pip-

      - name: Install PlatformIO
        id: install_platformio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

  build:
    needs: common
    if: needs.common.outputs.platformio_installed == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Restore PlatformIO cache
        uses: actions/cache@v4
        with:
          path: |-
            ~/.platformio
            ~/.cache/pip
          key: ${{ runner.os }}-platformio-pip-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-pip-

      - name: Install PlatformIO
        id: install_platformio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build
        run: platformio run -e default

  test:
    needs: common
    if: needs.common.outputs.platformio_installed == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Restore PlatformIO cache
        uses: actions/cache@v4
        with:
          path: |-
            ~/.platformio
            ~/.cache/pip
          key: ${{ runner.os }}-platformio-pip-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-platformio-pip-

      - name: Install PlatformIO
        id: install_platformio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Test
        run: platformio test -e native
