name: PlatformIO CI

on: [push]

jobs:
  common:
    runs-on: ubuntu-latest
    outputs:
      platformio_installed: ${{ steps.install_platformio.outcome }}
      platformio_bin_dir: ${{ steps.get_platformio_path.outputs.platformio_bin_dir }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v3
        id: setup-python
        with:
          python-version: "3.11"
      - name: Cache Python
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup-python.outputs.python-path }}
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/requirements.txt') }}
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Install PlatformIO
        id: install_platformio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Get PlatformIO Path
        id: get_platformio_path
        run: |
          PLATFORMIO_BIN_DIR=$(dirname $(which platformio))
          echo "platformio_bin_dir=${PLATFORMIO_BIN_DIR?}" >> ${GITHUB_OUTPUT?}

  build:
    needs: common
    if: needs.common.outputs.platformio_installed == 'success'
    runs-on: ubuntu-latest
    env:
      PLATFORMIO_BIN_DIR: ${{ needs.common.outputs.platformio_bin_dir }}
    steps:
      - uses: actions/checkout@v4
      - name: Add PlatformIO to PATH
        run: echo "${PLATFORMIO_BIN_DIR?}" >> ${GITHUB_PATH?}
      - name: Build
        run: platformio run -e default

  test:
    needs: common
    if: needs.common.outputs.platformio_installed == 'success'
    runs-on: ubuntu-latest
    env:
      PLATFORMIO_BIN_DIR: ${{ needs.common.outputs.platformio_bin_dir }}
    steps:
      - uses: actions/checkout@v4
      - name: Add PlatformIO to PATH
        run: echo "${PLATFORMIO_BIN_DIR?}" >> ${GITHUB_PATH?}
      - name: Test
        run: platformio test -e native
